### Confidence intervals

### for single population mean

In [1]:
import numpy as np
from scipy import stats

#### using t-distribution

In [30]:
# manual calculation
gfg_data = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 8, 10] 
sample_mean = np.mean(gfg_data)
sample_std = np.std(gfg_data)

print(f'{sample_mean=}')
print(f'{sample_std=}')

n = len(gfg_data)
df = n - 1

confidence_level = 0.95 
alpha = 1 - confidence_level

t_critical = stats.t.ppf(1 - alpha / 2,df)
# margin_of_error = z_critical * (sample_std / np.sqrt(n))
margin_of_error = t_critical * (stats.sem(gfg_data))
lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

print(f"Confidence Interval: ({lower_bound}, {upper_bound})")

sample_mean=3.9
sample_std=2.364318083507378
Confidence Interval: (2.7647191216978007, 5.035280878302199)


In [31]:
# using library
stats.t.interval(
    confidence_level, 
    df, 
    loc=sample_mean, 
    scale=stats.sem(gfg_data)
    )

(2.7647191216978007, 5.035280878302199)

#### using z-distribution

In [32]:
# using library
gfg_data = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 8, 10] 
stats.norm.interval( loc=np.mean(gfg_data), 
                 scale=stats.sem(gfg_data),
                   confidence=0.95) 

(2.836892469475994, 4.963107530524006)

In [33]:
# manual calculation
sample_mean = np.mean(gfg_data)
sample_std = np.std(gfg_data)

print(f'{sample_mean=}')
print(f'{sample_std=}')

n = len(gfg_data)
df = n - 1

confidence_level = 0.95 
alpha = 1 - confidence_level

z_critical = stats.norm.ppf(1 - alpha / 2)
# margin_of_error = z_critical * (sample_std / np.sqrt(n))
margin_of_error = z_critical * (stats.sem(gfg_data))
lower_bound = sample_mean - margin_of_error
upper_bound = sample_mean + margin_of_error

print(f"Confidence Interval: ({lower_bound}, {upper_bound})")


sample_mean=3.9
sample_std=2.364318083507378
Confidence Interval: (2.836892469475994, 4.963107530524006)


### for two population means
#### using z-distribution

In [34]:
# manual calculation
gfg_data1 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 8, 10] 
gfg_data2 = [1, 2, 3, 5,6, 6, 3, 7, 7, 7, 7, 4, 4, 5, 5, 5, 9, 6, 9, 10] 
sample_mean1 = np.mean(gfg_data1)
sample_mean2 = np.mean(gfg_data2)

sample_std1 = np.std(gfg_data1)
sample_std2 = np.std(gfg_data2)

print(f'{sample_mean1=}')
print(f'{sample_mean2=}')
print(f'{sample_std1=}')
print(f'{sample_std2=}')

n1 = len(gfg_data1)
n2 = len(gfg_data1)
df = n1 + n2 - 2

confidence_level = 0.95 
alpha = 1 - confidence_level

se1 = stats.sem(gfg_data1)
se2 = stats.sem(gfg_data2)
sed = np.sqrt(se1**2 + se2**2)

meand = sample_mean1 - sample_mean2

z_critical = stats.norm.ppf(1 - alpha / 2)
# margin_of_error = z_critical * (sample_std / np.sqrt(n))
margin_of_error = z_critical * (sed)
lower_bound = meand - margin_of_error
upper_bound = meand + margin_of_error

print(f"Confidence Interval: ({lower_bound}, {upper_bound})")


sample_mean1=3.9
sample_mean2=5.55
sample_std1=2.364318083507378
sample_std2=2.2907422377910613
Confidence Interval: (-3.1302526450304384, -0.1697473549695614)


In [35]:
stats.norm.interval( loc=meand, 
                 scale=sed,
                   confidence=0.95) 

(-3.1302526450304384, -0.1697473549695614)

#### using t-distribution

for equal variances

In [38]:
res = stats.ttest_ind(gfg_data1,gfg_data2,equal_var=True,alternative='two-sided')
ci=res.confidence_interval(confidence_level=0.95)
print("95 % confidence interval : ",np.round(ci,4))

95 % confidence interval :  [-3.1789 -0.1211]


In [53]:
# manual calculation
gfg_data1 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 8, 10] 
gfg_data2 = [1, 2, 3, 5,6, 6, 3, 7, 7, 7, 7, 4, 4, 5, 5, 5, 9, 6, 9, 10] 
sample_mean1 = np.mean(gfg_data1)
sample_mean2 = np.mean(gfg_data2)

sample_std1 = np.std(gfg_data1)
sample_std2 = np.std(gfg_data2)

print(f'{sample_mean1=}')
print(f'{sample_mean2=}')
print(f'{sample_std1=}')
print(f'{sample_std2=}')

n1 = len(gfg_data1)
n2 = len(gfg_data1)
df = n1 + n2 - 2

confidence_level = 0.95 
alpha = 1 - confidence_level

s1 = np.std(gfg_data1)
s2 = np.std(gfg_data2)
s_sqr = ((s1**2 * (n1-1)) + (s2**2 * (n2-1)))/df
sed = np.sqrt(s_sqr * ( (1/n1) + (1/n2) ))

meand = sample_mean1 - sample_mean2

t_critical = stats.t.ppf(1 - alpha / 2,df)
margin_of_error = t_critical * (sed)
lower_bound = meand - margin_of_error
upper_bound = meand + margin_of_error

print(f"Confidence Interval: ({lower_bound}, {upper_bound})")


sample_mean1=3.9
sample_mean2=5.55
sample_std1=2.364318083507378
sample_std2=2.2907422377910613
Confidence Interval: (-3.140200257725787, -0.15979974227421279)


In [54]:
# using library
ci =stats.t.interval(
    confidence_level, 
    df, 
    loc=meand, 
    scale=sed
    )
np.round(ci,2)

array([-3.14, -0.16])

---
for unequal variances

In [47]:
# manual calculation
gfg_data1 = [1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 8, 10] 
gfg_data2 = [1, 2, 3, 5,6, 6, 3, 7, 7, 7, 7, 4, 4, 5, 5, 5, 9, 6, 9, 10] 
sample_mean1 = np.mean(gfg_data1)
sample_mean2 = np.mean(gfg_data2)

sample_std1 = np.std(gfg_data1)
sample_std2 = np.std(gfg_data2)

print(f'{sample_mean1=}')
print(f'{sample_mean2=}')
print(f'{sample_std1=}')
print(f'{sample_std2=}')

n1 = len(gfg_data1)
n2 = len(gfg_data1)
df = n1 + n2 - 2

confidence_level = 0.95 
alpha = 1 - confidence_level

s1 = np.std(gfg_data1)
s2 = np.std(gfg_data2)

se1 = stats.sem(gfg_data1)
se2 = stats.sem(gfg_data2)
# sed = np.sqrt(se1**2 + se2**2)
sed = np.sqrt(s1**2 / n1 + s2**2 / n2)

w1 = (s1**2)/n1
w2 = (s2**2)/n2

t1 = stats.t.ppf(1-alpha/2,n1-1)
t2 = stats.t.ppf(1-alpha/2,n2-1)

meand = sample_mean1 - sample_mean2

t_critical = ( (w1*t1) + (w2*t2) )/(w1+w2)
margin_of_error = t_critical * (sed)
lower_bound = meand - margin_of_error
upper_bound = meand + margin_of_error

print(f"Confidence Interval: ({np.round(lower_bound,2)}, {np.round(upper_bound,2)})")


sample_mean1=3.9
sample_mean2=5.55
sample_std1=2.364318083507378
sample_std2=2.2907422377910613
Confidence Interval: (-3.19, -0.11)


In [50]:
res = stats.ttest_ind(gfg_data1,gfg_data2,equal_var=False,alternative='two-sided')
ci=res.confidence_interval(confidence_level=0.95)
print("95 % confidence interval : ",np.round(ci,2))

95 % confidence interval :  [-3.18 -0.12]


### for single population proportion

In [58]:
from statsmodels.stats.proportion import proportion_confint

In [60]:
ci=proportion_confint(count=204,nobs=591,alpha=0.05,method='normal')
np.round(ci,4)

array([0.3068, 0.3835])

### for two population proportions

In [62]:
from statsmodels.stats.proportion import confint_proportions_2indep

In [75]:
ci=confint_proportions_2indep(count1=60,nobs1=123,count2=18,nobs2=96,compare='diff',method='agresti-caffo',alpha=0.01,correction=True)
np.round(ci,4)

array([0.1397, 0.4485])

### for single population variance

In [18]:
import numpy as np
from scipy.stats import chi2

# Sample data
data = np.array([6.0,6.4,7.0,5.8,6.0,5.8,5.9,6.7,6.1,6.5,6.3,5.8])

# Degrees of freedom
df = len(data) - 1

# Sample variance
s2 = np.var(data, ddof=1)

# Confidence level
alpha = 0.05

# Confidence interval
crit0 = chi2.ppf(alpha/2,df)
crit1 = chi2.ppf(1-alpha/2,df)

# Confidence interval for variance
ci_var = [(df * s2) / crit1, (df * s2) / crit0]

print(f"The {(1-alpha)*100}% confidence interval for the population variance is [{ci_var[0]:.4f}, {ci_var[1]:.4f}].")


The 95.0% confidence interval for the population variance is [0.0771, 0.4427].


### for ratio of 2 population variances

In [25]:
import numpy as np
from scipy.stats import f

# Sample data
#data1 = np.array([6.0,6.4,7.0,5.8,6.0,5.8,5.9,6.7,6.1,6.5,6.3,5.8])
#data2 = np.array([6.0,6.4,7.0,5.8,6.0,5.8,5.9,6.7,6.1,6.5,6.3,5.8])

# Degrees of freedom
df1 = 11-1
df2 = 4-1

# Sample variance
s12 = 33.64
s22 = 11.56

# Confidence level
alpha = 0.05

# Confidence interval
crit0 = f.ppf(alpha/2,df1,df2)
crit1 = f.ppf(1-alpha/2,df1,df2)

# Confidence interval for variance
ci_var = [(s12 / s22) / crit1, (s12 / s22) / crit0]

print(f"The {(1-alpha)*100}% confidence interval for the population variance is [{ci_var[0]:.4f}, {ci_var[1]:.4f}].")


The 95.0% confidence interval for the population variance is [0.2018, 14.0427].
